# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Resources/UI/add_user.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(280, 321)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/mw_icons/add_user.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        Dialog.setWindowIcon(icon)
        Dialog.setStyleSheet("")
        self.gridLayout = QtWidgets.QGridLayout(Dialog)
        self.gridLayout.setObjectName("gridLayout")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setSpacing(20)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setSpacing(10)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(Dialog)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.name_edit = QtWidgets.QLineEdit(Dialog)
        self.name_edit.setMinimumSize(QtCore.QSize(0, 30))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.name_edit.setFont(font)
        self.name_edit.setStyleSheet("QLineEdit{\n"
"border: 2px solid #a3cef1;\n"
"border-radius: 5px;\n"
"}\n"
"QLineEdit:hover{\n"
"border-color: #77BEF8;\n"
"border-radius: 6px;\n"
"}")
        self.name_edit.setPlaceholderText("")
        self.name_edit.setObjectName("name_edit")
        self.horizontalLayout.addWidget(self.name_edit)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_4 = QtWidgets.QLabel(Dialog)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_5.addWidget(self.label_4)
        self.course_name = QtWidgets.QComboBox(Dialog)
        self.course_name.setMinimumSize(QtCore.QSize(180, 30))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.course_name.setFont(font)
        self.course_name.setStyleSheet("QComboBox{\n"
"border: 2px solid #a3cef1;\n"
"border-radius: 5px;\n"
"}\n"
"QComboBox:hover{\n"
"border-color: #77BEF8;\n"
"border-radius: 6px;\n"
"}\n"
"QComboBox::drop-down {\n"
"    subcontrol-origin: padding;\n"
"    subcontrol-position: top right;\n"
"    width: 18px;\n"
" \n"
"    border-left-width: 1px;\n"
"    border-left-color: darkgray;\n"
"    border-left-style: solid;\n"
"    border-top-right-radius: 3px;\n"
"    border-bottom-right-radius: 3px;\n"
"}\n"
"\n"
"\n"
"\n"
"QComboBox::down-arrow {\n"
"  image:  url(:/mw_icons/drop-down-arrow.png);\n"
"width: 20px;\n"
"}\n"
"QComboBox::drop-down:hover {\n"
"    background-color: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1, stop: 0 #d8d7d7, stop: 1 #e9e9e9);\n"
"}\n"
"\n"
"QComboBox::down-arrow:on { \n"
"    top: 1px;\n"
"    left: 1px;\n"
"}")
        self.course_name.setObjectName("course_name")
        self.course_name.addItem("")
        self.course_name.addItem("")
        self.course_name.addItem("")
        self.horizontalLayout_5.addWidget(self.course_name)
        self.verticalLayout.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setSpacing(10)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_2 = QtWidgets.QLabel(Dialog)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        self.phone_edit = QtWidgets.QLineEdit(Dialog)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.phone_edit.setFont(font)
        self.phone_edit.setStyleSheet("QLineEdit{\n"
"border: 2px solid #a3cef1;\n"
"border-radius: 5px;\n"
"}\n"
"QLineEdit:hover{\n"
"border-color: #77BEF8;\n"
"border-radius: 6px;\n"
"}")
        self.phone_edit.setInputMethodHints(QtCore.Qt.ImhNone)
        self.phone_edit.setPlaceholderText("")
        self.phone_edit.setObjectName("phone_edit")
        self.horizontalLayout_2.addWidget(self.phone_edit)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_3 = QtWidgets.QLabel(Dialog)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_3.addWidget(self.label_3)
        self.age_edit = QtWidgets.QSpinBox(Dialog)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.age_edit.setFont(font)
        self.age_edit.setStyleSheet("QSpinBox{\n"
"border: 2px solid #a3cef1;\n"
"border-radius: 5px;\n"
"}\n"
"QSpinBox:hover{\n"
"border-color: #77BEF8;\n"
"border-radius: 6px;\n"
"}")
        self.age_edit.setObjectName("age_edit")
        self.horizontalLayout_3.addWidget(self.age_edit)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.verticalLayout_2.addLayout(self.verticalLayout)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.cancel = QtWidgets.QPushButton(Dialog)
        font = QtGui.QFont()
        font.setFamily("Segoe UI Semibold")
        font.setPointSize(12)
        self.cancel.setFont(font)
        self.cancel.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.cancel.setStyleSheet("QPushButton{\n"
"background-color: white;\n"
"border: 2px solid #02ACE5;\n"
"min-width: 80px;\n"
"min-height: 24px;\n"
"color: #0096C7;\n"
"border-radius: 5px;\n"
"}\n"
"QPushButton:hover{\n"
"background-color: #02ACE5;\n"
"border: 2px solid #02ACE5;\n"
"min-width: 80px;\n"
"color: white;\n"
"}\n"
"QPushButton:pressed{\n"
"background-color: #09A2D4;\n"
"}")
        self.cancel.setObjectName("cancel")
        self.horizontalLayout_4.addWidget(self.cancel)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem1)
        self.ok = QtWidgets.QPushButton(Dialog)
        font = QtGui.QFont()
        font.setFamily("Segoe UI Semibold")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.ok.setFont(font)
        self.ok.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.ok.setStyleSheet("QPushButton{\n"
"background-color: white;\n"
"border: 2px solid #02ACE5;\n"
"min-width: 80px;\n"
"min-height: 24px;\n"
"color: #0096C7;\n"
"border-radius: 5px;\n"
"}\n"
"QPushButton:hover{\n"
"background-color: #02ACE5;\n"
"border: 2px solid #02ACE5;\n"
"min-width: 80px;\n"
"color: white;\n"
"}\n"
"QPushButton:pressed{\n"
"background-color: #09A2D4;\n"
"}")
        self.ok.setObjectName("ok")
        self.horizontalLayout_4.addWidget(self.ok)
        self.verticalLayout_2.addLayout(self.horizontalLayout_4)
        self.gridLayout.addLayout(self.verticalLayout_2, 0, 0, 1, 1)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)
        Dialog.setTabOrder(self.name_edit, self.course_name)
        Dialog.setTabOrder(self.course_name, self.phone_edit)
        Dialog.setTabOrder(self.phone_edit, self.age_edit)
        Dialog.setTabOrder(self.age_edit, self.ok)
        Dialog.setTabOrder(self.ok, self.cancel)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Add User"))
        self.label.setText(_translate("Dialog", "Name:"))
        self.label_4.setText(_translate("Dialog", "Course:"))
        self.course_name.setItemText(0, _translate("Dialog", "Web dasturlash"))
        self.course_name.setItemText(1, _translate("Dialog", "Robototexnika"))
        self.course_name.setItemText(2, _translate("Dialog", "3D modellashtirish"))
        self.label_2.setText(_translate("Dialog", "Phone:"))
        self.phone_edit.setInputMask(_translate("Dialog", "\\+\\9\\9\\899-999-99-99;_"))
        self.label_3.setText(_translate("Dialog", "Age:"))
        self.cancel.setText(_translate("Dialog", "Cancel"))
        self.ok.setText(_translate("Dialog", "OK"))
import res_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
